/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * POIs API
 * OpenAPI spec version: 1.0.0
 */

export type GetPoisSearchParams = {
/**
 * Coordenada X de referência
 * @minimum 0
 * @nullable
 */
x?: number | null;
/**
 * Coordenada Y de referência
 * @minimum 0
 * @nullable
 */
y?: number | null;
/**
 * Distância máxima de busca
 * @minimum 0
 * @nullable
 */
dmax?: number | null;
};
