/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * POIs API
 * OpenAPI spec version: 1.0.0
 */
import type { GetPoisSearch400DetailsItem } from './getPoisSearch400DetailsItem';

export type GetPoisSearch400 = {
  success: boolean;
  error: string;
  details?: GetPoisSearch400DetailsItem[];
};
