/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * POIs API
 * OpenAPI spec version: 1.0.0
 */

export type GetPois200Item = {
  id: number;
  name: string;
  x: number;
  y: number;
  createdAt: string;
  updatedAt: string;
};
