/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * POIs API
 * OpenAPI spec version: 1.0.0
 */

export type PostPoisBody = {
  /**
     * Nome do Ponto de Interesse
     * @minLength 1
     * @maxLength 255
     */
  name: string;
  /**
     * Coordenada X
     * @minimum 0
     */
  x: number;
  /**
     * Coordenada Y
     * @minimum 0
     */
  y: number;
};
