/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * POIs API
 * OpenAPI spec version: 1.0.0
 */
import type { PostPois409DetailsItem } from './postPois409DetailsItem';

export type PostPois409 = {
  success: boolean;
  error: string;
  details?: PostPois409DetailsItem[];
};
