/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * POIs API
 * OpenAPI spec version: 1.0.0
 */
import type { PostPois400DetailsItem } from './postPois400DetailsItem';

export type PostPois400 = {
  success: boolean;
  error: string;
  details?: PostPois400DetailsItem[];
};
