/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * POIs API
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetPois200Item,
  GetPoisSearch200Item,
  GetPoisSearchParams,
  PostPois201,
  PostPoisBody
} from '../model';




  export const getPOIsAPI = (axiosInstance: AxiosInstance = axios.default) => {
/**
 * Cadastra um novo POI passando nome e coordenadas X e Y.
 * @summary Cadastrar um novo Ponto de Interesse
 */
const postPois = (
    postPoisBody?: PostPoisBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostPois201>> => {
    return axiosInstance.post(
      `/pois`,
      postPoisBody,options
    );
  }

/**
 * Retorna uma lista com todos os POIs cadastrados no banco de dados.
 * @summary Listar todos os Pontos de Interesse
 */
const getPois = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetPois200Item[]>> => {
    return axiosInstance.get(
      `/pois`,options
    );
  }

/**
 * Retorna uma lista de POIs que estão dentro de uma distância máxima a partir de uma coordenada de referência.
 * @summary Buscar POIs por proximidade
 */
const getPoisSearch = (
    params?: GetPoisSearchParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetPoisSearch200Item[]>> => {
    return axiosInstance.get(
      `/pois/search`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

return {postPois,getPois,getPoisSearch}};
export type PostPoisResult = AxiosResponse<PostPois201>
export type GetPoisResult = AxiosResponse<GetPois200Item[]>
export type GetPoisSearchResult = AxiosResponse<GetPoisSearch200Item[]>
